"""empty message

Revision ID: 1d70eec7f477
Revises: 441df302f3dc
Create Date: 2024-01-25 10:13:31.032739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d70eec7f477'
down_revision = '441df302f3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.Integer(), nullable=True))
        batch_op.drop_column('is_favorite')
        batch_op.drop_column('favorite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('card_id')

    # ### end Alembic commands ###
