"""empty message

Revision ID: 441df302f3dc
Revises: 5b81abfeb365
Create Date: 2024-01-25 08:49:57.815093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441df302f3dc'
down_revision = '5b81abfeb365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
