"""empty message

Revision ID: 495d76d7ca95
Revises: d53a0d94a084
Create Date: 2023-09-25 11:32:32.113672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495d76d7ca95'
down_revision = 'd53a0d94a084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
