"""empty message

Revision ID: 5b81abfeb365
Revises: 4068e9209cf0
Create Date: 2024-01-24 12:27:57.420013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b81abfeb365'
down_revision = '4068e9209cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
