"""empty message

Revision ID: 878238fcadff
Revises: c2d6c1b9dc61
Create Date: 2024-01-28 18:36:30.629295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878238fcadff'
down_revision = 'c2d6c1b9dc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
